steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'pirate-translator', '--runtime=python311', '--trigger-http', '--entry-point=transform_file', '--no-allow-unauthenticated', '--region=us-central1', '--source=.']
