steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        gcloud functions deploy summarize-text \
          --region us-west1 \
          --runtime python310 \
          --trigger-http \
          --entry-point hello_gcs \
          --set-env-vars PROJECT_ID=my-new-test-project-447723 \
          --no-allow-unauthenticated

timeout: 1600s
